-- 6-5
-- 날짜 형식 지정해 SYSDATE 출력
SELECT 
TO_CHAR(SYSDATE, 'YYYY/MM/DD HH24:MI:SS') AS 현재날짜시간
FROM DUAL;

-- 여러가지 숫자 형식 사용해 급여 출력
SELECT SAL,
TO_CHAR(SAL, 'L999,999') AS SAL_L,
TO_CHAR(SAL, '$999,999') AS SAL_$
FROM EMP;

-- TO_NUMBER
SELECT 1300 - '1500',
'1300' + 1500
FROM DUAL;

SELECT TO_DATE('2026-01-06', 'YYYY-MM-DD') AS TODATE1,
TO_DATE('2026/01/06', 'YYYY/MM/DD') AS TODATE2
FROM DUAL;

-- NULL 처리 함수
SELECT
NVL(COMM, 0)
FROM EMP;

SELECT
NVL(ENAME, 1)
FROM EMP;

SELECT 1 FROM DUAL
UNION ALL
SELECT 1 FROM DUAL;

SELECT EMPNO, ENAME, COMM,
NVL2(COMM, 'O', 'X'),
DECODE(COMM,
0,'X', NULL, 'X','O'),
NVL2(COMM, SAL*12+COMM, SAL*12) AS ANNSAL
FROM EMP;

/*
NVL
IF VALUE != NUMM THEN
RETURN VALUE
ELSE
TEXT, NUMBER
END

DECODE(1,
2,3,
4,5,
6)
IF 1 == 2 THEN
3
ELSE
4
END
*/

-- DECODE 함수 사용해서 출력
SELECT EMPNO, ENAME, JOB, SAL,
DECODE(JOB,
'MANAGER', SAL*1.1,
'SALESMAN', SAL*1.05,
'ANALYST' , SAL,
SAL*1.03) AS UPSAL
FROM EMP;

-- CASE문 사용해서 출력
SELECT EMPNO, ENAME, JOB, SAL,
CASE JOB
WHEN 'MANAGER' THEN SAL*1.1
WHEN 'SALESMAN' THEN SAL*1.05
WHEN 'ANALYST' THEN SAL
ELSE SAL*1.03
END AS UPSAL
FROM EMP;

SELECT EMPNO, ENAME, JOB, SAL,
CASE JOB
WHEN 'MANAGER' THEN 1
WHEN 'SALESMAN' THEN 2
WHEN 'ANALYST' THEN 3
ELSE 4
END AS UPSAL
FROM EMP;

-- 열에 따라서 출력이 달라지는 CASE문
SELECT EMPNO, ENAME, COMM,
CASE
    WHEN COMM IS NULL THEN '해당 사항 없음'
WHEN COMM = 0 THEN '수당 없음'
WHEN COMM > 0 THEN '수장 : ' || COMM
END AS COMM_TEXT
FROM EMP;

-- 접합 연산자를 사용하여 부서별 평균 급여 출력
SELECT AVG(SAL), '10' AS DEPTNO FROM EMP WHERE DEPTNO = 10
UNION ALL
SELECT AVG(SAL), '10' AS DEPTNO FROM EMP WHERE DEPTNO = 20
UNION ALL
SELECT AVG(SAL), '10' AS DEPTNO FROM EMP WHERE DEPTNO = 30;

-- GROUP BY 사용
SELECT AVG(SAL), DEPTNO FROM EMP
GROUP BY DEPTNO;

-- DEPT 테이블 복사 후 DEPT_TEMP 테이블 만들기
CREATE TABLE DEPT_TEMP
AS SELECT * FROM DEPT;

