-- P.347
-- 1.
-- 1)
CREATE TABLE EMPIDX AS SELECT * FROM EMP;

-- 2)
CREATE INDEX IDX_EMPIDX_EMPNO ON EMPIDX(EMPNO);

-- 3)
SELECT * FROM USER_IND_COLUMNS WHERE TABLE_NAME = 'EMPIDX';


-- 2.
CREATE OR REPLACE VIEW EMPIDX_OVER15K AS
SELECT EMPNO, ENAME, JOB, DEPTNO, SAL,
       NVL2(COMM, 'O', 'X') AS COMM
FROM EMPIDX
WHERE SAL > 1500;


-- 3.
-- 1)
CREATE TABLE DEPTSEQ AS SELECT * FROM DEPT;

-- 2)
CREATE SEQUENCE SEQ_DEPTSEQ
    START WITH 1     
    INCREMENT BY 1    
    MAXVALUE 99      
    MINVALUE 1       
    NOCYCLE          
    NOCACHE;         

-- 3)
INSERT INTO DEPTSEQ (DEPTNO, DNAME, LOC) VALUES (SEQ_DEPTSEQ.NEXTVAL, 'DATABASE', 'SEOUL');
INSERT INTO DEPTSEQ (DEPTNO, DNAME, LOC) VALUES (SEQ_DEPTSEQ.NEXTVAL, 'WEB', 'BUSAN');
INSERT INTO DEPTSEQ (DEPTNO, DNAME, LOC) VALUES (SEQ_DEPTSEQ.NEXTVAL, 'MOBILE', 'ILSAN');

