SELECT * FROM EMP
WHERE ENAME LIKE '%S';


SELECT * FROM EMP
WHERE DEPTNO = 30
AND JOB = 'SALESMAN';


SELECT * FROM EMP
WHERE DEPTNO = 20 AND SAL > 2000

UNION

SELECT * FROM EMP
WHERE DEPTNO = 30 AND SAL > 2000;


SELECT * FROM EMP
WHERE SAL NOT BETWEEN 2000 AND 3000;

SELECT * FROM EMP
WHERE SAL < 2000 OR SAL > 3000;


SELECT * FROM EMP
WHERE ENAME LIKE '%E%'
AND DEPTNO = 30
AND SAL NOT BETWEEN 1000 AND 2000;


SELECT * FROM EMP
WHERE COMM IS NULL
AND JOB IN ('MANAGER', 'CLERK')
AND ENAME NOT LIKE '_L%';