SELECT ENAME FROM EMP
WHERE LOWER(ENAME) = 'scott';


SELECT ENAME FROM EMP
WHERE ENAME LIKE UPPER('%sc%');


SELECT LOWER(ENAME) AS "ENAME", UPPER(JOB) AS "JOB"
FROM EMP;


SELECT ENAME, LENGTH(ENAME) 
FROM EMP
WHERE LENGTH(ENAME) <= 5;

