CREATE TABLE DEPT_TEMP
    AS SELECT * FROM DEPT;

-- 10-2
SELECT * FROM DEPT_TEMP;

-- 10-3
INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
                VALUES (50, 'DATABASE', 'SEOUL');

SELECT * FROM DEPT_TEMP;

INSERT INTO DEPT_TEMP (DEPTNO, DNAME     ,LOC)
                VALUES (60   , 'NEWYORK'     );


-- 10-5
INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
                VALUES (70   , 'WEB', NULL);

SELECT * FROM DEPT_TEMP;

-- 10-6
INSERT INTO DEPT_TEMP (DEPTNO, DNAME    ,LOC)
                VALUES (80   , 'MOBILE', '');

SELECT * FROM DEPT_TEMP;

-- 10-7
INSERT INTO DEPT_TEMP (DEPTNO, LOC)
                VALUES(90    , 'INCHEON');

SELECT * FROM DEPT_TEMP;

-- 10-8
CREATE TABLE EMP_TEMP
    AS SELECT *
        FROM EMP 
       WHERE 1 <> 1;

SELECT * FROM EMP_TEMP;

-- 10-12
INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB. MGR,
                        HIREDATE,
                        SAL, COMM, DEPTNO)
                    VALUES (2111, '이순신', 'MANAGER', 9999,
                             TO_DATE('07/01/2001', 'DD/MM/YYYY'),
                             4000, NULL, 20);

SELECT * FROM EMP_TEMP;

-- 10-13
INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
                VALUES (3111, '심청이', 'MANAGER', 9999, SYSDATE, 4000, NULL, 30);

SELECT * FROM EMP_TEMP;

-- 10-14
INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
    SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM, E.DEPTNO
     FROM EMP E, SALGRADE S 
    WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
     AND S.GRADE =1;

SELECT * FROM EMP_TEMP;

-- 10-15
CREATE TABLE DEPT_TEMP2
    AS SELECT * FROM DEPT;

SELECT * FROM DEPT_TEMP2;

-- 10-16
UPDATE DEPT_TEMP2
    SET LOC = 'SEOUL';

SELECT * FROM DEPT_TEMP2;

-- 10-18
UPDATE DEPT_TEMP2
    SET DNAME = 'DATABASE',
        LOC   = 'SEOUL'
WHERE DEPTNO = 40;

SELECT * FROM DEPT_TEMP2;

-- P.266 1분 복습
UPDATE EMP_TEMP
    SET COMM = 50
WHERE SALL <= 2500;

-- 10-21
UPDATE DEPT_TEMP2
    SET LOC = 'SEOUL'
WHERE DEPTNO = (SELECT DEPTNO
                 FROM DEPT_TEMP2
                WHERE DNAME='OPERATIONS');

SELECT * FROM DEPT_TEMP2;

-- 10-22
CREATE TABLE EMP_TEMP2
    AS SELECT * FROM EMP;

SELECT * FROM EMP_TEMP2;

-- 10-23
DELETE FROM EMP_TEMP2
 WHERE JOB = 'MANAGER';

SELECT * FROM EMP_TEMP2;

-- 10-24
DELETE FROM EMP_TWMP2
    WHERE EMPNO IN (SELECT E.EMPNO
                      FROM EMP_TEMP2 E, SALGRADE S
                    WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
                     AND S.GRADE = 3
                     AND DEPTNO = 30);

SELECT * FROM EMP_TEMP2;

-- P.271 1분 복습
DELETE FROM EMP_TEMP2
    WHERE SAL >= 3000;

-- 11-6
SELECT * FROM DEPT_TCL;

-- 12-1
CREATE TABLE EMP_DDL(
    EMPNO    NUMBER(4),
    ENAME    VARCHAR2(10),
    JOB      VARCHAR2(9),
    MGR      NUMBER(4),
    HIREDATE DATE,
    SAL      NUMBER(7,2),
    DEPTNO   NUMBER(7,2),
    DEPTNO   NUMBER(2)
);

DESC EMP_DDL;

-- 12-6
CREATE TABLE EMP_ALTER
    AS SELECT * FROM EMP;

SELECT * FROM EMP_ALTER;

-- 12-7
ALTER TABLE EMP_ALTE
    ADD HP VARCHAR2(20);

SELECT * FROM EMP_ALTER;

-- 12-8
ALTER TABLE EMP_ALTER
    RENAME COLUMN HP TO TEL;

SELECT * FROM EMP_ALTER;

-- 12-9
ALTER TABLE EMP_ALTER
MODIFY EMPNO NUMBER(5);

DESC EMP_ALTER;

-- 12-10
ALTER TABLE EMP_ALTER
DROP COLUMN TEL;

SELECT * FROM EMP_ALTER;

-- 14-1
CREATE TABLE TABLE_NOTNULL(
    LOGIN_ID VARCHAR2(20) NOT NULL,
    LOGIN_PWD VARCHAR2(20) NOT NULL,
    TEL       VARCHAR2(20)
);

DESC TABLE_NOTNULL;

-- 14-2
INSERT INTO TABLE_NOTNULL (LOGIN_ID, LOGIN_PWD, TEL)
VALUES ('TEST_ID_01', NULL, '010-1234-5678');

-- 14-7
ALTER TABLE TABLE_NOTNULL
MODIFY(TEL NOT NULL);

-- 14-14
CREATE TABLE TABLE_UNIQUE(
    LOGIN_ID VARCHAR2(20) UNIQUE,
    LOGIN_PWD VARCHAR2(20) NOT NULL,
    TEL       VARCHAR2(20)
);

DESC TABLE_NOTNULL;

-- 14-16
INSERT INTO TABLE_UNIQUE(LOGIN_ID, LOGIN_PWD, TEL)
VALUES('TEST_ID_01', 'PWD01', '010-1234-5678');

SELECT * FROM TABLE_UNIQUE;

-- 14-17
INSERT INTO TABLE_UNIQUE (LOGIN_ID, LOGIN_PWD, TEL)
VALUES ('TEST_ID_01', 'PWD01', '010-1234-5678');

-- 14-18
INSERT INTO TABLE_UNIQUE(LOGIN_ID, LOGIN_PWD, TEL)
VALUES('TEST_ID_02', 'PWD01', '010-1234-5678');

SELECT * FROM TABLE_UNIQUE;

-- 14-19
INSERT INTO TABLE_UNIQUE(LOGIN_ID, LOGIN_PWD, TEL)
VALUES(NULL, 'PWD01', '010-2345-6789');

SELECT * FROM TABLE_UNIQUE;

-- 14-20
UPDATE TABLE_UNIQUE
    SET LOGIN_ID = 'TEST_ID_01'
WHERE LOGIN_ID IS NULL;

-- 14-29
CREATE TABLE TABLE_PK(
    LOGIN_ID VARCHAR2(20) PRIMARY KEY,
    LOGIN_PWD VARCHAR2(20) NOT NULL,
    TEL       VARCHAR2(20)
);

DESC TABLE_PK;

-- 14-39
CREATE TABLE DEPT_FK(
    DEPTNO NUMBER(2) CONSTRAINT DEPTFK_DEPTNO_PK PRIMARY KEY,
    DNAME  VARCHAR2(14),
    LOC    VARCHAR2(13)
);

DESC DEPT_FK;

-- 14-40
CREATE TABLE EMP_FK(
    EMPTNO  NUMBER(4) CONSTRAINT EMPFK_EMPNO_PK PRIMARY KEY,
    ENAME   VARCHAR2(10),
    JOB     VARCHAR2(9),
    MGR     NUMBER(4),
    HIREDATE DATE,
    SAL     NUMBER(7,2),
    COMM    NUMBER(7,2),
    DEPTNO  NUMBER(2) CONSTRAINT EMPFK_DEPTNO_FK REFERENCES DEPT_FK (DEPTNO)
);

DESC EMP_FK;

-- 14-41
INSERT INTO EMP_FK
VALUES(9999, 'TEST_NAME', 'TEST_JOB', NULL, TO_DATE('2001/01/01', 'YYYY/MM/DD'),
       3000, NULL, 10);

-- 14-42
INSERT INTO DEPT_FK
VALUES(10, 'TEST_DNAME', 'TEST_LOC');

SELECT * FROM DEPT_FK;

-- 14-43
INSERT INTO EMP_FK
VALUES(9999, 'TEST_NAME', 'TEST_JOB', NULL, TO_DATE('2001/01/01', 'YYYY/MM/DD'),
       3000, NULL, 10);

SELECT * FROM DEPT_FK;

--14-44
DELETE FROM DEPT_FK
WHERE DEPTNO = 10;
