-- 입사 20주년 되는 날짜 출력
 SELECT EMPNO, ENAME, HIREDATE,
 ADD_MONTHS(HIREDATE, 240) AS WORK20YEAR
 FROM EMP;

 -- 입사 40년 초과한 사원 데이터 출력
 SELECT EMPNO,
 ENAME, HIREDATE, SYSDATE
 FROM EMP 
 WHERE ADD_MONTHS(HIREDATE, 480) < SYSDATE;

-- NEXT_DAY, LAST_DAY 함수 사용해서 출력
 SELECT SYSDATE,
 NEXT_DAY(SYSDATE, '월요일'),
 LAST_DAY(SYSDATE)
 FROM DUAL;

 -- 최초 입사자와 각각 입사자의 근무 일차 출력
 -- 사번, 이름, 입사일 ,차이일
 -- 1) 최초 입사자의 일자를 카피 -> 날짜-날짜
 SELECT ENAME, HIREDATE
FROM EMP
ORDER BY HIREDATE;
-- ='17/12/1980 12:00:00'

SELECT ENAME, HIREDATE, HIREDATE - TO_DATE('1980-12-17')
FROM EMP
ORDER BY HIREDATE;

-- 최초 입사자와 1년 이상 차이나는 사람 조회
SELECT ENAME, HIREDATE, HIREDATE - TO_DATE('1980-12-17')
FROM EMP
WHERE (HIREDATE - TO_DATE('1980-12-17')) >= 365
ORDER BY HIREDATE;

-- P.179~180
--1)
SELECT EMPNO,
       RPAD(SUBSTR(EMPNO, 1, 2), 4, '*') AS MASKING_EMPNO,
       ENAME,
       RPAD(SUBSTR(ENAME, 1, 1), LENGTH(ENAME), '*') AS MASKING_ENAME
FROM EMP
WHERE LENGTH(ENAME) >= 5 AND LENGTH(ENAME) < 6
ORDER BY EMPNO;

--2) 
SELECT EMPNO, ENAME, SAL,
TRUNC(SAL / 21.5, 2) AS DAY_PAY,
       ROUND((SAL / 21.5) / 8, 1) AS TIME_PAY
FROM EMP
ORDER BY EMPNO;

--3) 
SELECT EMPNO, ENAME, HIREDATE,
       TO_CHAR(NEXT_DAY(ADD_MONTHS(HIREDATE, 3), '월요일'), 'YYYY-MM-DD') AS R_JOB,
       NVL(TO_CHAR(COMM), 'N/A') AS COMM
FROM EMP
ORDER BY EMPNO;

--4)
SELECT EMPNO, ENAME, MGR,
       CASE 
           WHEN MGR IS NULL THEN '0000'
           WHEN SUBSTR(MGR, 1, 2) = '75' THEN '5555'
           WHEN SUBSTR(MGR, 1, 2) = '76' THEN '6666'
           WHEN SUBSTR(MGR, 1, 2) = '77' THEN '7777'
           WHEN SUBSTR(MGR, 1, 2) = '78' THEN '8888'
           ELSE TO_CHAR(MGR)
       END AS CHG_MGR 
FROM EMP
ORDER BY EMPNO;


-- P.200
--1)
SELECT DEPTNO,
       TRUNC(AVG(SAL)) AS AVG_SAL,
       MAX(SAL) AS MAX_SAL,
       MIN(SAL) AS MIN_SAL,
       COUNT(*) AS CNT
FROM EMP
GROUP BY DEPTNO
    ORDER BY MIN_SAL;

--2)
SELECT JOB, COUNT(*)
FROM EMP
GROUP BY JOB
HAVING COUNT(*) >= 3
ORDER BY JOB;

--3)
SELECT TO_CHAR(HIREDATE, 'YYYY') AS HIRE_YEAR,
       DEPTNO,
       COUNT(*) AS CNT
FROM EMP
GROUP BY TO_CHAR(HIREDATE, 'YYYY'), DEPTNO
ORDER BY HIRE_YEAR;

--4) 
SELECT NVL2(COMM, 'O', 'X') AS EXIST_COMM,
       COUNT(*) AS CNT
FROM EMP
GROUP BY NVL2(COMM, 'O', 'X');

