SELECT
    E1.EMPNO,
    E1.ENAME,
    E1.MGR,
    E2.EMPNO,
    E2.ENAME
-- FROM EMP E1, EMP E2
FROM EMP E1
    -- LEFT OUTER JOIN EMP E2 ON (E2.EMPNO = E1.MGR)
    RIGHT OUTER JOIN EMP E2 ON (E2.EMPNO = E1.MGR);
-- WHERE E2.EMPNO = E1.MGR(+)

SELECT *
FROM EMP_TEM E, SALGRADE_TEM S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
ORDER BY EMP;

-- P.225

-- P.226 ~ 227
-- 1.
    --1)
    SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.SAL
    FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO
    AND E.SAL > 2000
    ORDER BY D.DEPTNO;
    --2)
    SELECT DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.SAL
    FROM EMP E JOIN DEPT D USING (DEPTNO)
    WHERE E.SAL > 2000
    ORDER BY DEPTNO;

--2.
    --1)
    SELECT D.DEPTNO, D.DNAME, 
    TRUNC(AVG(E.SAL)) AS AVG_SAL, 
    MAX(E.SAL) AS MAX_SAL, 
    MIN(E.SAL) AS MIN_SAL, 
    COUNT(*) AS CNT
    FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO
    GROUP BY D.DEPTNO, D.DNAME
    ORDER BY D.DEPTNO;
    --2)
    SELECT DEPTNO, D.DNAME, 
    TRUNC(AVG(E.SAL)) AS AVG_SAL, 
    MAX(E.SAL) AS MAX_SAL, 
    MIN(E.SAL) AS MIN_SAL, 
    COUNT(*) AS CNT
    FROM EMP E JOIN DEPT D USING (DEPTNO)
    GROUP BY DEPTNO, D.DNAME
    ORDER BY DEPTNO;

--3.
    --1)
    SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.JOB, E.SAL
    FROM EMP E, DEPT D
    WHERE E.DEPTNO(+) = D.DEPTNO 
    ORDER BY D.DEPTNO, E.ENAME;
    --2)
    SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.JOB, E.SAL
    FROM DEPT D LEFT OUTER JOIN EMP E ON (D.DEPTNO = E.DEPTNO)
    ORDER BY D.DEPTNO, E.ENAME;

--4.
    --1)
   SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.MGR, E.SAL, D.DEPTNO AS DEPTNO_1,
       S.LOSAL, S.HISAL, S.GRADE,
       M.EMPNO AS MGR_EMPNO, M.ENAME AS MGR_ENAME
    FROM EMP E, DEPT D, SALGRADE S, EMP M
    WHERE E.DEPTNO(+) = D.DEPTNO
        AND E.SAL BETWEEN S.LOSAL(+) AND S.HISAL(+)
        AND E.MGR = M.EMPNO(+)
    ORDER BY D.DEPTNO, E.EMPNO;
    
    --2)


-- 9-3
SELECT *
    FROM EMP
    WHERE SAL > (SELECT SAL
                 FROM EMP
                 WHERE ENAME ='JONES');

-- 9-4
SELECT *
    FROM EMP
   WHERE HIREDATE < (SELECT HIREDATE
                      FROM EMP
                      WHERE ENAME = 'SCOTT');

-- 9-18
SELECT *
    FROM EMP 
    WHERE (DEPTNO, SAL) IN (SELECT DEPTNO, MAX(SAL)
                                FROM EMP
                                GROUP BY DEPTNO);


            
