-- 등가 조인
-- 오류
SELECT 
EMPNO, 
ENAME, 
DEPTNO, 
DNAME, 
LOC
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO;
-- 올바름
SELECT 
E.EMPNO, 
E.ENAME, 
D.DEPTNO, 
D.DNAME, 
D.LOC
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
ORDER BY D.DEPTNO, E.EMPNO;

SELECT 
E.EMPNO, 
E.ENAME, 
D.DEPTNO, 
D.DNAME, 
D.LOC
-- FROM EMP E, DEPT D, SALGRADE S
FROM EMP E
JOIN DEPT D ON (E.DEPTNO = D.DEPTNO)
--WHERE E. DEPTNO = D.DEPTNO
WHERE E.EMPNO = 7788;


SELECT
    E.ENAME, D.*
    FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO
    AND D.LOC = 'CHICAGO';


    SELECT E.EMPNO, E.ENAME, D.DEPTNO, D.DNAME, D.LOC
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
AND E.SAL <= 2500
AND E.EMPNO <=9999;


-- 비등가 조인
SELECT *
FROM EMP E, SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL;

SELECT *
FROM EMP E, SALGRADE S
WHERE E.SAL <= S.HISAL
ORDER BY EMPNO;

SELECT 
E1.EMPNO,
E1.ENAME,
E1.MGR,
E2.EMPNO,
E2.ENAME
FROM EMP E1, EMP E2
WHERE E1.MGR(+) = E2.EMPNO;

SELECT
E.EMPNO,
E.ENAME,
E.DEPTNO,
D.DEPTNO AS DNO,
D.DNAME
FROM EMP E, DEPT D 
WHERE E.DEPTNO(+) = D.DEPTNO;

-- 같은 테이블 두 번 사용해 자체 조인
SELECT E1.EMPNO, E1.ENAME, E1.MGR,
E2.EMPNO AS MGR_EMPNO,
E2.ENAME AS MGR_ENAME
FROM EMP E1, EMP E2
WHERE E1.MGR = E2.EMPNO;

--왼쪽 외부 조인
SELECT E1.EMPNO, E1.ENAME, E1.MGR,
E2.EMPNO AS MGR_EMPNO,
E2.ENAME AS MGR_ENAME
FROM EMP E1, EMP E2
WHERE E1.MGR = E2.EMPNO(+)
ORDER BY E1.EMPNO;

--오른쪽 외부 조인
SELECT E1.EMPNO, E1.ENAME, E1.MGR,
E2.EMPNO AS MGR_EMPNO,
E2.ENAME AS MGR_ENAME
FROM EMP E1, EMP E2
WHERE E1.MGR(+) = E2.EMPNO
ORDER BY E1.EMPNO;